###POST https://suporte-portfolio.app.n8n.cloud/webhook-test/assistente-pessoal

POST https://suporte-portfolio.app.n8n.cloud/webhook/assistente-pessoal
Content-Type: application/json

{
    "chatId": "123456",
    "mensagem": " Voce trabalha com Oi ?"
}